project_name: deletify
machines:
  - user: stg # default: admin
    pass: stg # default: admin
    # root_pass: <root-pass> # default: root
    # port: <port> # default: generate random port
    # passwd_auth: <yes-or-no> # default: no
    # ip: <ip-address> # default: generate random IP
    # ram: <ram> # default: 1024
    # cpus: <processors> # default: 1
    # disk_size: <size> # default: 10GB
    # box: <box-name> # default: ubuntu/bionic64
